version: "3"

services:
  nginx:
    container_name: nginx
    restart: unless-stopped
    image: nginx
    ports:
      - 8000:80
      - 8090:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./localhost/:/etc/letsencrypt/live/localhost/
